/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Ui_Package;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sonal
 */
public class ManagerMainPageUi extends javax.swing.JFrame {

    /**
     * Creates new form ManagerMainPageUi
     */
    public ManagerMainPageUi() {
        initComponents();
        this.setTitle("Apple iStore / Manager Panel");
        loardAllProductTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        txtSearchProductName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbSearchProductCategory = new javax.swing.JComboBox();
        btnSearchProduct = new javax.swing.JButton();
        btnAddNewProduct = new javax.swing.JButton();
        btnCreateNewUser = new javax.swing.JButton();
        btnViewAllProducts = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 1, 36)); // NOI18N
        jLabel1.setText("Welcome to Apple iStore");

        tblProducts.setAutoCreateRowSorter(true);
        tblProducts.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Product Name", "Category", "Price"
            }
        ));
        tblProducts.setToolTipText("");
        jScrollPane1.setViewportView(tblProducts);

        txtSearchProductName.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        txtSearchProductName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchProductNameActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Product Name   :");

        cmbSearchProductCategory.setEditable(true);
        cmbSearchProductCategory.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        cmbSearchProductCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select Category", "iPhone", "Apple Watch", "iPad", "AirPods", "Mac" }));
        cmbSearchProductCategory.setToolTipText("");
        cmbSearchProductCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmbSearchProductCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSearchProductCategoryActionPerformed(evt);
            }
        });

        btnSearchProduct.setBackground(new java.awt.Color(0, 0, 225));
        btnSearchProduct.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnSearchProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnSearchProduct.setText("Search");
        btnSearchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchProductActionPerformed(evt);
            }
        });

        btnAddNewProduct.setBackground(new java.awt.Color(0, 0, 225));
        btnAddNewProduct.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnAddNewProduct.setForeground(new java.awt.Color(255, 255, 255));
        btnAddNewProduct.setText("Add New Product");
        btnAddNewProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewProductActionPerformed(evt);
            }
        });

        btnCreateNewUser.setBackground(new java.awt.Color(0, 0, 225));
        btnCreateNewUser.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnCreateNewUser.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateNewUser.setText("Create New User");
        btnCreateNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateNewUserActionPerformed(evt);
            }
        });

        btnViewAllProducts.setBackground(new java.awt.Color(0, 0, 225));
        btnViewAllProducts.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnViewAllProducts.setForeground(new java.awt.Color(255, 255, 255));
        btnViewAllProducts.setText("View All Product");
        btnViewAllProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAllProductsActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 737, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSearchProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmbSearchProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnViewAllProducts)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAddNewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCreateNewUser))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchProductName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSearchProductCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddNewProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewAllProducts, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchProductNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchProductNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchProductNameActionPerformed

    private void btnSearchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchProductActionPerformed

        String searchProductName = txtSearchProductName.getText();
        String productCategory = cmbSearchProductCategory.getSelectedItem().toString();
       
        if((searchProductName.equals("")) && (productCategory.equals("Select Category"))){
            JOptionPane.showMessageDialog(null, "Please Type Of Product Name Or Select The Product Category .....", "WARNING !!", JOptionPane.WARNING_MESSAGE);
        }
        else if(searchProductName.equals("")){
            loardProductInCategoryTable(productCategory);
        }
        else if(productCategory.equals("Select Category")){
            loardProductInNameTable(searchProductName);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please Select One Searching Option .....", "WARNING !!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchProductActionPerformed

    private void cmbSearchProductCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSearchProductCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSearchProductCategoryActionPerformed

    private void btnAddNewProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewProductActionPerformed
        AddNewProductUi addNewProductUi = new AddNewProductUi();
        addNewProductUi.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnAddNewProductActionPerformed

    private void btnCreateNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateNewUserActionPerformed
        UserRegisterUi userRegisterUi = new UserRegisterUi();
        userRegisterUi.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnCreateNewUserActionPerformed

    private void btnViewAllProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAllProductsActionPerformed
        loardAllProductTable();
        txtSearchProductName.setText("");
        cmbSearchProductCategory.setSelectedIndex(0);
    }//GEN-LAST:event_btnViewAllProductsActionPerformed

    public void loardAllProductTable(){
        
        String filePath = "E:\\sonal project\\project\\Apple_iStore\\src\\Data_Store\\productData.txt" ;
        File file = new File(filePath);
        
        try {
            
            DefaultTableModel model = (DefaultTableModel)tblProducts.getModel();
            BufferedReader bufferedReader = new BufferedReader(new FileReader(file));
            
            model.setRowCount(0);
            
            Object[] tableLines = bufferedReader.lines().toArray();
            for(int i=0 ; i<tableLines.length ; i++){
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(",");
                model.addRow(dataRow);
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ManagerMainPageUi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void loardProductInCategoryTable(String category){
        
        String filePath = "E:\\sonal project\\project\\Apple_iStore\\src\\Data_Store\\productData.txt" ;
        File file = new File(filePath);
        
        txtSearchProductName.setText("");
        
        try {
            
            DefaultTableModel model = (DefaultTableModel)tblProducts.getModel();
            BufferedReader bufferedReader = new BufferedReader(new FileReader(file));
            
            model.setRowCount(0);
            
            Object[] tableLines = bufferedReader.lines().toArray();
            for(int i=0 ; i<tableLines.length ; i++){
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(",");
                if(category.equals(dataRow[2])){
                    model.addRow(dataRow);
                } 
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ManagerMainPageUi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void loardProductInNameTable(String productName){
        
        String filePath = "E:\\sonal project\\project\\Apple_iStore\\src\\Data_Store\\productData.txt" ;
        File file = new File(filePath);
        
        cmbSearchProductCategory.setSelectedIndex(0);
        
        try {
            
            DefaultTableModel model = (DefaultTableModel)tblProducts.getModel();
            BufferedReader bufferedReader = new BufferedReader(new FileReader(file));
            
            model.setRowCount(0);
            
            Object[] tableLines = bufferedReader.lines().toArray();
            for(int i=0 ; i<tableLines.length ; i++){
                String line = tableLines[i].toString().trim();
                String[] dataRow = line.split(",");
                if(productName.equals(dataRow[1])){
                    model.addRow(dataRow);
                } 
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ManagerMainPageUi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerMainPageUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerMainPageUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerMainPageUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerMainPageUi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerMainPageUi().setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewProduct;
    private javax.swing.JButton btnCreateNewUser;
    private javax.swing.JButton btnSearchProduct;
    private javax.swing.JButton btnViewAllProducts;
    private javax.swing.JComboBox cmbSearchProductCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tblProducts;
    private javax.swing.JTextField txtSearchProductName;
    // End of variables declaration//GEN-END:variables
}
